from model.book import Book

Books: list[Book] = [
    Book(
        id=1,
        title="The Pragmatic Programmer",
        author="Andrew Hunt and David Thomas",
        category="programming",
        description="Practical advice and philosophy for software developers to write flexible, maintainable code.",
    ),
    Book(
        id=2,
        title="Clean Code",
        author="Robert C. Martin",
        category="programming",
        description="Guidelines and best practices for producing readable, maintainable, and efficient code.",
    ),
    Book(
        id=3,
        title="1984",
        author="George Orwell",
        category="dystopian",
        description="A dystopian novel about pervasive government surveillance and totalitarianism.",
    ),
    Book(
        id=4,
        title="Pride and Prejudice",
        author="Jane Austen",
        category="romance",
        description="A classic novel exploring manners, upbringing, and marriage in 19th-century England.",
    ),
    Book(
        id=5,
        title="Moby-Dick",
        author="Herman Melville",
        category="adventure",
        description="An intense tale of obsession as Captain Ahab pursues the white whale.",
    ),
    Book(
        id=6,
        title="The Catcher in the Rye",
        author="J.D. Salinger",
        category="fiction",
        description="A coming-of-age story capturing teenage alienation and rebellion.",
    ),
    Book(
        id=7,
        title="Brave New World",
        author="Aldous Huxley",
        category="dystopian",
        description="A futuristic society engineered for stability at the cost of individuality.",
    ),
    Book(
        id=8,
        title="The Hobbit",
        author="J.R.R. Tolkien",
        category="fantasy",
        description="Bilbo Baggins' adventure that leads into the larger Lord of the Rings saga.",
    ),
    Book(
        id=9,
        title="Fahrenheit 451",
        author="Ray Bradbury",
        category="dystopian",
        description="A story about censorship where books are outlawed and 'firemen' burn them.",
    ),
    Book(
        id=10,
        title="Jane Eyre",
        author="Charlotte Brontë",
        category="romance",
        description="The experiences of an orphaned governess and her moral and emotional growth.",
    ),
    Book(
        id=11,
        title="The Fellowship of the Ring",
        author="J.R.R. Tolkien",
        category="fantasy",
        description="The first volume of the epic quest to destroy the One Ring.",
    ),
    Book(
        id=12,
        title="The Alchemist",
        author="Paulo Coelho",
        category="fiction",
        description="A fable about following your dreams and listening to your heart.",
    ),
    Book(
        id=13,
        title="The Odyssey",
        author="Homer",
        category="epic",
        description="Odysseus' long journey home after the Trojan War, filled with trials and adventures.",
    ),
    Book(
        id=14,
        title="Crime and Punishment",
        author="Fyodor Dostoevsky",
        category="fiction",
        description="A psychological exploration of guilt, conscience, and redemption.",
    ),
    Book(
        id=15,
        title="The Picture of Dorian Gray",
        author="Oscar Wilde",
        category="fiction",
        description="A tale about vanity, moral corruption, and the supernatural.",
    ),
    Book(
        id=16,
        title="Sapiens: A Brief History of Humankind",
        author="Yuval Noah Harari",
        category="non-fiction",
        description="A sweeping overview of human history from the Stone Age to the modern era.",
    ),
    Book(
        id=17,
        title="The Road",
        author="Cormac McCarthy",
        category="post-apocalyptic",
        description="A sparse, moving story of a father and son surviving in a devastated world.",
    ),
    Book(
        id=18,
        title="Thinking, Fast and Slow",
        author="Daniel Kahneman",
        category="non-fiction",
        description="An examination of the two systems that drive human thought and decision-making.",
    ),
    Book(
        id=19,
        title="Guns, Germs, and Steel",
        author="Jared Diamond",
        category="non-fiction",
        description="An analysis of how environment and geography shaped the modern world.",
    ),
    Book(
        id=20,
        title="The Handmaid's Tale",
        author="Margaret Atwood",
        category="dystopian",
        description="A novel that explores themes of power, gender, and religious extremism in a totalitarian state.",
    ),
]
